about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='about-home'),
]

index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index-home'),
]

library_project/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('about/',include('about.urls')),
    path('mentor/',include('mentor.urls')),
    path('mailus/',include('mailus.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
]

mailus/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='mailus-home'),
]

mentor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='mentor-home'),
]

about/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models

# Create your models here.

mailus/models.py
from django.db import models

# Create your models here.

mentor/models.py
from django.db import models

# Create your models here.
class mentor_detail(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=30)
    department_choice = (
        ('CO','Computer'),
        ('IT','InformationTechnology'),
        ('MECH','Mechanical'),
        ('EXTC','Electronics'),
    )
    department = models.CharField(max_length=4, choices=department_choice)
    image_link = models.CharField(max_length=100)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

about/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'about/about.html', {'title':'Library Project'})

index/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index/index.html', {'title':'Library Project'})

mailus/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'mailus/mailus.html', {'title':'Mail US'})

mentor/views.py
from django.shortcuts import render
from .models import mentor_detail

def home(request):
    context = {
        'mentors' : mentor_detail.objects.all()
    }
    return render(request, 'mentor/mentor.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm

def register(request):
    if request.method == 'post':
        form = UserRegisterForm()
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.sucess(request, f'Account Created Sucessfully, {username}')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

about/templates/about/about.html
{% extends "index/base.html" %}
{% load static %}
{% block content %}
  <div class="banner1">

  </div>
  <div class="team-page">
    <div class="container">
      <h3 class="agile">Team</h3>
      <div class="col-md-4 about-poleft">
            <div class="about_img"><img src="{% static 'images/kunj.jpg' %}" width="350" height="450">
                <h5>Kunj Haria</h5>
                <div class="about_opa">
                  <p>kunj.ch@somaiya.edu</p>
                    <p>Social</p>
                    <div class="agile-social">
                      <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                      </ul>
                    </div>
                </div>
            </div>
          </div>
      <div class="col-md-4 about-poleft">
              <div class="about_img"><img src="{% static 'images/tanish.jpg' %}" width="350" height="450">
                <h5>Tanish Sehgal</h5>
                <div class="about_opa">
                  <p>tanish.sehgal@somaiya.edu</p>
                  <p>Social</p>
                   <div class="agile-social">
                <ul>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-rss"></i></a></li>
                </ul>
              </div>
                </div>
              </div>
          </div>
      <div class="col-md-4 about-poleft">
              <div class="about_img"><img src="{% static 'images/simith.jpg' %}" width="350" height="450">
                <h5>Simith Bhojani</h5>
                <div class="about_opa">
                  <p>simith.bhojani@somaiya.edu</p>
                  <p>Social</p>
                  <div class="agile-social">
                <ul>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-rss"></i></a></li>
                </ul>
              </div>
                </div>
              </div>
          </div>
      <div class="clearfix"></div>
    </div>
  </div>
{% endblock content%}

index/templates/index/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- js -->
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- //js -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />

    <!-- font-awesome icons -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <!-- //font-awesome icons -->
    <link href="//fonts.googleapis.com/css?family=Alegreya:400,400i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>Project Library</title>
    {% endif %}
  </head>
  <body>
    <div class="header-w3l">
      <div class="container">
        <nav class="navbar navbar-default">
          <div class="navbar-header navbar-left">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="wthree_logo">
              <h1><a class="navbar-brand" href="{% url 'index-home' %}">Project Library</a></h1>
            </div>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
            <nav>
              <ul class="nav navbar-nav link-effect-5" id="link-effect-5">
                <li class="active"><a href="{% url 'index-home' %}" data-hover="Home">Home</a></li>
                <li><a href="{% url 'about-home' %}" data-hover="About">About</a></li>
                <li><a href="{% url 'mentor-home' %}" data-hover="Mentors">Mentors</a></li>
                <li><a href="{% url 'mailus-home' %}" data-hover="Mail Us">Mail Us</a></li>
                <li><a href="" data-hover="Projects">Projects</a></li>
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" data-hover="Logout">Logout</a></li>
                  {% else %}
                    <li><a href="{% url 'login' %}" data-hover="Login">Login</a></li>
                    <li><a href="{% url 'register' %}" data-hover="Register">Register</a></li>
                  {% endif %}
              </ul>
              <div class="w3_social_icons">
                <div class="cd-main-header">
                  <a class="cd-search-trigger" href="#cd-search"> <span></span></a>
                </div>
                <div id="cd-search" class="cd-search">
                  <form action="#" method="post">
                    <input name="Search" type="search" placeholder="Search...">
                  </form>
                </div>
              </div>
              <div class="clearfix"></div>
            </nav>
          </div>
        </nav>
      </div>
    </div>

    {% if message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    <!-- footer -->
    	<div class="footer">
    		<div class="container">
    			<div class="col-md-4 w3_footer_grid">
    				<h3>About Us</h3>
    				<p>
              Our Aim is to provide a platform where all information about the projects done by the department from
              both UG and PG courses would be available along with all the details of the mentor and various memebers.
            </p>
    			</div>
    			<div class="col-md-3 w3_footer_grid">
    				<h3>Navigation</h3>
    				<ul>
    					<li class="active"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'index-home' %}">Home</a></li>
    					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'about-home' %}">About</a></li>
    					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'mentor-home' %}">Mentors</a></li>
    					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'mailus-home' %}">Mail Us</a></li>
              <li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'mailus-home' %}">Projects</a></li>
              {% if user.is_authenticated %}
                <li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'login' %}">Login</a></li>
                <li><i class="fa fa-long-arrow-right" aria-hidden="true"></i><a href="{% url 'register' %}">Register</a></li>
              {% endif %}
    				</ul>
    			</div>
    			<div class="col-md-5 w3_footer_grid">
    				<h3>Newsletter</h3>
    				<form action="#" method="post">
    					<input type="email" name="email" placeholder="Your email..." required="">
    					<input type="submit" value=" ">
    				</form>
    				</div>
    			<div class="clearfix"> </div>
    			<div class="w3layouts_footer_grid">
    				<div class="clearfix"> </div>
    			</div>
          <div class="copyright_content d-flex flex-row align-items-center">
            <div>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | K.J Somaiya College Of Engineering, Vidyavihar | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">3 Idiots</a>
            </div>
        </div>
    		</div>
    	</div>
    <!-- //footer -->
    <!-- for bootstrap working -->
    	<script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- //for bootstrap working -->
  </body>
</html>

index/templates/index/index.html
{% extends "index/base.html" %}
{% load static %}
{% block content %}
  <!-- banner -->
    <div class="banner">
      <div class="container">
        <section class="slider">
          <div class="flexslider">
            <ul class="slides">
              <li>
                <div class="banner_info">
                  <h3>Project Library</h3>
                  <p>Find the most intuitive projects of the department.</p>
                </div>
              </li>
              <li>
                <div class="banner_info">
                  <h3>Mentors</h3>
                  <p>The most supportive mentors.</p>
                </div>
              </li>
            </ul>
          </div>
        </section>
        <!-- flexSlider -->
          <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
          <script type="text/javascript">
            $(window).load(function(){
              $('.flexslider').flexslider({
              animation: "slide",
              start: function(slider){
                $('body').removeClass('loading');
              }
              });
            });
          </script>
        <!-- //flexSlider -->
      </div>
    </div>
  <!-- //banner -->
  <!-- tabs -->
  <div class="tabs">
      <div class="tabs-left">
        <div class="col-xs-2 tab-grid-left"> <!-- required for floating -->
          <!-- Nav tabs -->
           <ul class="nav nav-tabs">
            <li class="active"><a href="#Tab1" data-toggle="tab" aria-expanded="false">Innovation</a></li>
            <li class=""><a href="#Tab2" data-toggle="tab" aria-expanded="false">Ideas</a></li>
            <li class=""><a href="#Tab3" data-toggle="tab" aria-expanded="false">Creativity</a></li>
            <li class=""><a href="#Tab4" data-toggle="tab" aria-expanded="false">Problem Solving</a></li>
            <li class=""><a href="#Tab5" data-toggle="tab" aria-expanded="true">Inspiration</a></li>
          </ul>
        </div>
        <div class="col-xs-10 tab-grid-right">
          <!-- Tab panes -->
          <div class="tab-content">
            <div class="tab-pane active" id="Tab1">
              <div class="col-md-6 w3-text">
                <h3>Innovation</h3>
                <p>Every once in a while, a new technology, an old problem, and a big idea turn into an innovation.</p>
              </div>
              <div class="col-md-6 w3-imga">
                <img src="{% static 'images/innovation.jpg' %}" class="img-responsive" alt="">
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="tab-pane" id="Tab2">
              <div class="col-md-6 w3-imga">
                <img src="{% static 'images/ideas.jpg' %}" class="img-responsive" alt="">
              </div>
              <div class="col-md-6 w3-text">
                <h3>Ideas</h3>
                <p>
                  Great minds discuss ideas;
                  average minds discuss events;
                  small minds discuss people.
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="tab-pane" id="Tab3">
              <div class="col-md-6 w3-text">
                <h3>Creativity</h3>
                <p>Without change there is no innovation, creativity, or incentive for improvement. Those who initiate change will have a better opportunity to manage the change that is inevitable.</p>
              </div>
              <div class="col-md-6 w3-imga">
                <img src="{% static 'images/creativity.jpg' %}" class="img-responsive" alt="">
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="tab-pane" id="Tab4">
              <div class="col-md-6 w3-imga">
                <img src="{% static 'images/problem-solving.jpg' %}" class="img-responsive" alt="">
              </div>
              <div class="col-md-6 w3-text">
                <h3>Problem Solving</h3>
                <p>After every storm the sun will smile; for every problem there is a solution, and the soul's indefeasible duty is to be of good cheer.</p>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="tab-pane" id="Tab5">
              <div class="col-md-6 w3-text">
                <h3>Inspiration</h3>
                <p>Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.</p>
              </div>
              <div class="col-md-6 w3-imga">
                <img src="{% static 'images/Inspiration.jpg' %}" class="img-responsive" alt="">
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
  </div>
  <!-- //tabs -->
{% endblock content %}

mailus/templates/mailus/mailus.html
{% extends "index/base.html" %}
{% load static %}
{% block content %}
  <div class="banner1"></div>
  <!-- mail -->
    <div class="contact wthree-2">
    		<div class="container">
    			<h3 class="agile">Mail Us</h3>
    			<div class="ser-t">
    				<b></b>
    				<span><i></i></span>
    				<b class="line"></b>
    			</div>
    			<form action="#" method="post">
    			<div class="contact-grids1 w3agile-6">
    						<div class="col-md-6 contact-form1">
    							<h4>Name</h4>
    							<input type="text" name="Name" placeholder="" required="">
    						</div>
    						<div class="col-md-6 contact-form1 ag">
    							<h4>Email</h4>
    							<input type="email" name="Email" placeholder="" required="">
    						</div>

    						<div class="clearfix"> </div>
    				<div class="contact-me animated wow slideInUp" data-wow-delay=".5s">
    					<h4>Message</h4>

    						<textarea name="Message" placeholder="" required=""> </textarea>


    				</div>
    				<div class="contact-form">
    							<input type="submit" value="Submit">
    						</div>
    			</div>
    			</form>
    			<div class="contact-grids agile-1">
    				<div class="col-md-4 contact-grid agileinfo-6">
    					<div class="contact-grid1">
    						<div class="con-ic">
    							<i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>
    						</div>

    							<h4>Address</h4>
    							<p>Somaiya Campus, Vidyanagar, Vidyavihar <span>Mumbai.</span></p>

    					</div>
    				</div>
    				<div class="col-md-4 contact-grid agileinfo-6">
    					<div class="contact-grid1">
    						<div class="con-ic">
    							<i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>
    					</div>
    							<h4>Call Us</h4>
    							<p>91-22-66449191<span><a href="https://www.somaiya.edu/kjsce/">Website</a></span></p>

    					</div>
    				</div>
    				<div class="col-md-4 contact-grid agileinfo-6">
    					<div class="contact-grid1">
    						<div class="con-ic">
    							<i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
    						</div>
    							<h4>Email</h4>
    							<p><a href="mailto:enquiry@engg.somaiya.edu">enquiry@engg.somaiya.edu</a></p>

    					</div>
    				</div>
    				<div class="clearfix"> </div>
    			</div>
    		</div>
    	</div>
    	<div class="map">
        <iframe src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;coord=19.074599,72.899672&amp;q=Vidyanagar%2C%20Vidya%20Vihar%20East%2C%20Ghatkopar%20East%2C%20Mumbai%2C%20Maharashtra%20400077+(Somaiya%20College)&amp;ie=UTF8&amp;t=&amp;z=17&amp;iwloc=A&amp;output=embed" allowfullscreen></iframe>
    	</div>

    <!-- //mail -->
{% endblock content %}

mentor/templates/mentor/mentor.html
{% extends "index/base.html" %}
{% load static %}

{% block content %}

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <script src="{% static 'js/modernizr.min.js' %}"></script>
  <script src="{% static 'js/jquery.fitvids.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <div class="banner1">

  </div>
    <!-- gallery -->
    <div class="w3l-gallery">
      <div class="container" style="">
        <div class="galley-grid">
          <h3 class="agile">Mentors</h3>
          <span class="lft-bar-gallery"> </span>
          <span class="rit-bar-gallery"> </span>
        </div>
        {% for mentor in mentors %}
          <div class="w3ls-top">
          <div class="col-md-4 project">
            <div class="projectThumbnail">
              <div class="projectThumbnailHover projcet-ro">
                <h4>{{ mentor.name }}</h4>
                <h5>{{ mentor.email }}</h5>
              </div>
                <img src="{% static mentor.image_link }} %}" alt="" class="img-responsive thumbnailImage" width="340" height="150">
              </div>
              <div class="projectInfo">
                <div class="projectNavClose">
                  <button class="closeButton"><img src="{% static 'images/cross.png' %}" alt=""></button>
                </div>
                <div class="clearfix"> </div>
                <h4>{{ mentor.name }}</h4>
                <h4>{{ mentor.get_department_display }}</h4>
                <p>{{ mentor.email }}</p>

              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <!-- //gallery -->
{% endblock content %}

users/templates/users/login.html
{% extends "index/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="banner1"></div>
  <div class="w3l-gallery">
    <div class="container" style="">
      <div class="galley-grid">
        <h3 class="agile">Login Now</h3>
        <span class="lft-bar-gallery"> </span>
        <span class="rit-bar-gallery"> </span>
      </div>
      <div class="content-section">
        <form  method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form|crispy }}
          </div>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit" name="button">Log In</button>
          </div>
        </form>
        <div class="border-top pt-3">
          <small class="text-muted">Need a Account ? <a href="{% url 'register' %}" class="ml-2">Register</a></small>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "index/base.html" %}
{% load static %}
{% block content %}
  <div class="banner1"></div>
  <h2>You have been Logged Out Sucessfully</h2>
    <div class="border-top pt-3">
      <small class="text-muted"><a href="{% url 'login' %}" class="ml-2">Login In Again</a></small>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "index/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="banner1"></div>
  <!-- gallery -->
  <div class="w3l-gallery">
    <div class="container" style="">
      <div class="galley-grid">
        <h3 class="agile">Register Now</h3>
        <span class="lft-bar-gallery"> </span>
        <span class="rit-bar-gallery"> </span>
      </div>
      <div class="content-section">
        <form  method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form|crispy }}
          </div>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit" name="button">Sign Up</button>
          </div>
        </form>
        <div class="border-top pt-3">
          <small class="text-muted">Already Have An Account ? <a href="{% url 'login' %}" class="ml-2">Login</a></small>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}